development:
  clients:
    default:
      database: pictures_api_development
      hosts:
        - localhost:27017
      options:
        allow_dynamic_fields: false
        identity_map_enabled: true
        include_root_in_json: true
        include_type_for_serialization: true
        scope_overwrite_exception: true
        skip_version_check: false
        use_activesupport_time_zone: false
        use_utc: true
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: pictures_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
